config/routes.rb
Rails.application.routes.draw do
  resources :vehicles, :rides, :routes, :stops_prices, :stops, :rewards, :reservations, :driver_rides, :secretary_hours, :refuelings
  resources :reward_statuses, except: :new
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  root 'pages#index'
  get 'price_list' => 'pages#price_list'
  get 'before_new' => 'reservations#before_new'
  get 'rewards_list' => 'pages#rewards_list'
  post 'payment' => 'reservations#payment'
  post 'payment_process' => 'reservations#payment_process'

end

app/models/driver_ride.rb
class DriverRide < ActiveRecord::Base
  belongs_to :user
  belongs_to :ride
  has_many :reservations

  validates_presence_of :date, :ride_id
end

app/models/order_of_stop.rb
class OrderOfStop < ActiveRecord::Base
  belongs_to :stop
  belongs_to :route
end

app/models/refueling.rb
class Refueling < ActiveRecord::Base
  belongs_to :vehicle

  validates_presence_of :capacity, :price
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :driver_ride
  belongs_to :stops_price
  attr_accessor :ride

  def friendly_name
    "#{driver_ride.try(:ride).try(:route).try(:friendly_name)} <strong>#{date} #{driver_ride.try(:ride).startTime.strftime("%k:%M")}</strong>"
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :users, :through => :reward_statuses
  validates_presence_of :title,:description, :price

  has_attached_file :avatar, :styles => { :medium => "300x300>", :small => "100x100#", :large => "700x700>" },
                    :processors => [:cropper],
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :processing
  after_update :reprocess_avatar, :if => :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
  end

  private
  def reprocess_avatar
    return unless (cropping? && !processing)
    self.processing = true
    avatar.reprocess!
    self.processing = false
  end

end

app/models/reward_status.rb
class RewardStatus < ActiveRecord::Base
  belongs_to :reward
  belongs_to :user

  def status_name
    case status
      when 1
        "Oczekuje na rozpatrzenie"
      when 2
        "Oczekuje na wysyłkę"
      when 3
        "Wysłano"
      else
        "Błąd"
    end
  end
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  has_many :driver_rides
  belongs_to :vehicle
  belongs_to :route
  has_and_belongs_to_many :week_days

  def friendly_name
    days = ""
    week_days.each do |w|
      days += w.friendly_name + " "
    end
    "#{route.friendly_name} - #{startTime.strftime("%k:%M")} - #{end_time} - #{days}"
  end

  def end_time
    (startTime + route.order_of_stops.order(:order).last.time * 60).strftime("%k:%M")
  end

  def stop_time stop
    if time =  route.order_of_stops.order(:order).find(stop).time
      (startTime + time * 60).strftime("%k:%M")
    else
      (startTime).strftime("%k:%M")
    end
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :rides
  has_many :order_of_stops, :dependent => :destroy
  has_many :stops, :through => :order_of_stops

  accepts_nested_attributes_for :order_of_stops, :allow_destroy => true

  def friendly_name
    "#{id}: #{order_of_stops.order(:order).first.try(:stop).try(:city_with_place)} -> #{order_of_stops.order(:order).last.try(:stop).try(:city_with_place)}"
  end
end

app/models/secretary_hours.rb
class SecretaryHours < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :week_days
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  has_many :routes, :through => :order_of_stops
  has_many :stops_prices_start, :class_name => 'StopsPrice', :foreign_key => 'startStop_id'
  has_many :stops_prices_end, :class_name => 'StopsPrice', :foreign_key => 'endStop_id'

  validates_presence_of :city, :place

  def city_with_place
    "#{city} - #{place}"
  end
end

app/models/stops_price.rb
class StopsPrice < ActiveRecord::Base
  belongs_to :startStop, :class_name => 'Stop', :foreign_key => 'startStop_id'
  belongs_to :endStop, :class_name => 'Stop', :foreign_key => 'endStop_id'

  def friendly_name
    "#{startStop.city_with_place} - #{endStop.city_with_place} - #{price}PLN"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards, :through => :reward_statuses
  has_many :reservations
  has_many :secretary_hourses
  has_many :driver_rides

  validates_presence_of :firstName, :lastName

  def friendly_name
    "#{firstName} #{lastName}"
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :rides
  has_many :refuelings

  validates_presence_of :brand, :model

  def friendly_name
    "#{id}: #{brand} - #{model}"
  end
end

app/models/week_day.rb
class WeekDay < ActiveRecord::Base
  has_and_belongs_to_many :rides
  has_and_belongs_to_many :secretary_hours

  def friendly_name
    case id
      when 1
        "Pn"
      when 2
        "Wt"
      when 3
        "Śr"
      when 4
        "Cz"
      when 5
        "Pt"
      when 6
        "Sb"
      when 7
        "Nd"
      else
        puts "You gave me #{id} -- I have no idea what to do with that."
    end
  end
end

app/controllers/stops_prices_controller.rb
class StopsPricesController < ApplicationController
  before_action :authenticate_user!
  before_action :user_check_owner

  def new
    @stopPrice = StopsPrice.new
    @stops = Stop.all
  end

  def edit
    @stopPrice = StopsPrice.find(params[:id])
    @stops = Stop.all
  end

  def create
    @stopPrice = StopsPrice.new(stops_prices_params)
    if @stopPrice.save
      redirect_to @stopPrice
    else
      flash[:alert] = "Wystąpiły błędy"
      render 'new'
    end
  end

  def update
    @stopPrice = StopsPrice.find(params[:id])

    if @stopPrice.update(stops_prices_params)
      redirect_to @stopPrice
    else
      flash[:alert] = "Wystąpiły błędy"
      render 'edit'
    end
  end

  def destroy
    @stopPrice = StopsPrice.find(params[:id])
    @stopPrice.destroy

    redirect_to stops_prices_path
  end

  def show
    @stopPrice = StopsPrice.find(params[:id])
  end

  def index
    @stopPrice = StopsPrice.all
  end


  private
  def stops_prices_params
    params.require(:stops_price).permit(:price, :startStop_id, :endStop_id)

  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/refuelings_helper.rb
module RefuelingsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def link_to_function(name, *args, &block)
    html_options = args.extract_options!.symbolize_keys

    function = block_given? ? update_page(&block) : args[0] || ''
    onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'

    content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end

end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/stops_prices_helper.rb
module StopsPricesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/stops_prices/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6 col-md-offset-3">
    <h1 class="text-center login-title"><%= yield(:action) %> cenę</h1>
    <hr>
    <div class="account-wall">
      <%= form_for @stopPrice, :html => { :multipart => true, class: 'form-signin' } do |f| %>

        <% if @stopPrice.errors.any? %>
          <div id="error_explanation">
            <h2>
              Wystąpiły następujące błędy
            </h2>
            <ul>
              <% @stopPrice.errors.full_messages.each do |msg| %>
                <li>Pole <%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.label :price %>
        <%= f.text_field :price, type: "number", class: "form-control", required: true %>
        <%= f.label :startStop %>
        <%= f.select :startStop_id, @stops.collect {|a| [a.city_with_place, a.id]}, {}, class: 'form-control' -%>
        <%= f.label :endStop %>
        <%= f.select :endStop_id, @stops.collect {|a| [a.city_with_place, a.id]}, {}, class: 'form-control' -%>
        <p>
        <table>
          <tr>
            <td><%= f.submit 'Zapisz', class: 'btn btn-primary'%></td>
            <td style="padding-left:5px;"><%= link_to 'Powrót', stops_prices_path, class: 'btn btn-default' %></td>
          </tr>
        </table>
        </p>
      <% end %>

    </div>
  </div>
</div>

app/views/stops_prices/edit.html.erb
<% content_for (:action) do %>
  Edytuj
<% end %>
<%= render 'form' %>

app/views/stops_prices/index.html.erb
<hr style="margin:40px 0;">

<h1 style="float:left;">Ceny przejazdów</h1>
<%= link_to 'Dodaj', new_stops_price_path, class: 'btn btn-primary', style: 'float:right; margin-top:25px;' %>

<hr style="clear:both;"/>

<table class="table table-striped table-hover">
  <tr>
    <th>Przystanek początkowy</th>
    <th>Przystanek końcowy</th>
    <th>Cena przejazdu</th>
    <th style="width:5%;"></th>
    <th style="width:5%;"></th>
  </tr>
  <% @stopPrice.order(:id).each do |stopPrice| %>
    <tr>

      <td class="clickable-row" data-href='<%= stops_price_path(stopPrice) %>'><%= stopPrice.startStop.try(:city_with_place) %></td>
      <td class="clickable-row" data-href='<%= stops_price_path(stopPrice) %>'><%= stopPrice.endStop.try(:city_with_place) %></td>
      <td class="clickable-row" data-href='<%= stops_price_path(stopPrice) %>'><%= stopPrice.try(:price) %>zł</td>

      <td><%= link_to 'Edycja', edit_stops_price_path(stopPrice), class: 'btn btn-default btn-sm' %></td>
      <td><%= link_to 'Usuń', stops_price_path(stopPrice), method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć?'}, class: 'btn btn-primary btn-sm' %></td>
    </tr>
  <% end %>
</table>

app/views/stops_prices/new.html.erb
<% content_for (:action) do %>
  Dodaj
<% end %>
<%= render 'form' %>

app/views/stops_prices/show.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6 col-md-offset-3">
    <h3><strong>Cena przejazdu</strong></h3>
    <h4><%= @stopPrice.price %></h4>
    <hr />
    <h3><strong>Trasa</strong></h3>
    <h4><%= @stopPrice.startStop.city_with_place %> <strong>-></strong> <%= @stopPrice.endStop.city_with_place %></h4>
    <br />

    <%= link_to 'Edycja', edit_stops_price_path(@stopPrice), class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Usuń', stops_price_path(@stopPrice), method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć?'}, class: 'btn btn-primary btn-sm' %>

    <%= link_to 'Powrót', stops_prices_path, class: 'btn btn-default' %>
  </div>
</div>