config/routes.rb
Rails.application.routes.draw do
  resources :vehicles, :rides, :routes, :stops_prices, :stops, :rewards, :reservations, :driver_rides, :secretary_hours, :refuelings
  resources :reward_statuses, except: :new
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  root 'pages#index'
  get 'price_list' => 'pages#price_list'
  get 'before_new' => 'reservations#before_new'
  get 'rewards_list' => 'pages#rewards_list'
  post 'payment' => 'reservations#payment'
  post 'payment_process' => 'reservations#payment_process'

end

app/models/driver_ride.rb
class DriverRide < ActiveRecord::Base
  belongs_to :user
  belongs_to :ride
  has_many :reservations

  validates_presence_of :date, :ride_id
end

app/models/order_of_stop.rb
class OrderOfStop < ActiveRecord::Base
  belongs_to :stop
  belongs_to :route
end

app/models/refueling.rb
class Refueling < ActiveRecord::Base
  belongs_to :vehicle

  validates_presence_of :capacity, :price
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :driver_ride
  belongs_to :stops_price
  attr_accessor :ride

  def friendly_name
    "#{driver_ride.try(:ride).try(:route).try(:friendly_name)} <strong>#{date} #{driver_ride.try(:ride).startTime.strftime("%k:%M")}</strong>"
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :users, :through => :reward_statuses
  validates_presence_of :title,:description, :price

  has_attached_file :avatar, :styles => { :medium => "300x300>", :small => "100x100#", :large => "700x700>" },
                    :processors => [:cropper],
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :processing
  after_update :reprocess_avatar, :if => :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
  end

  private
  def reprocess_avatar
    return unless (cropping? && !processing)
    self.processing = true
    avatar.reprocess!
    self.processing = false
  end

end

app/models/reward_status.rb
class RewardStatus < ActiveRecord::Base
  belongs_to :reward
  belongs_to :user

  def status_name
    case status
      when 1
        "Oczekuje na rozpatrzenie"
      when 2
        "Oczekuje na wysyłkę"
      when 3
        "Wysłano"
      else
        "Błąd"
    end
  end
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  has_many :driver_rides
  belongs_to :vehicle
  belongs_to :route
  has_and_belongs_to_many :week_days

  def friendly_name
    days = ""
    week_days.each do |w|
      days += w.friendly_name + " "
    end
    "#{route.friendly_name} - #{startTime.strftime("%k:%M")} - #{end_time} - #{days}"
  end

  def end_time
    (startTime + route.order_of_stops.order(:order).last.time * 60).strftime("%k:%M")
  end

  def stop_time stop
    if time =  route.order_of_stops.order(:order).find(stop).time
      (startTime + time * 60).strftime("%k:%M")
    else
      (startTime).strftime("%k:%M")
    end
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :rides
  has_many :order_of_stops, :dependent => :destroy
  has_many :stops, :through => :order_of_stops

  accepts_nested_attributes_for :order_of_stops, :allow_destroy => true

  def friendly_name
    "#{id}: #{order_of_stops.order(:order).first.try(:stop).try(:city_with_place)} -> #{order_of_stops.order(:order).last.try(:stop).try(:city_with_place)}"
  end
end

app/models/secretary_hours.rb
class SecretaryHours < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :week_days
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  has_many :routes, :through => :order_of_stops
  has_many :stops_prices_start, :class_name => 'StopsPrice', :foreign_key => 'startStop_id'
  has_many :stops_prices_end, :class_name => 'StopsPrice', :foreign_key => 'endStop_id'

  validates_presence_of :city, :place

  def city_with_place
    "#{city} - #{place}"
  end
end

app/models/stops_price.rb
class StopsPrice < ActiveRecord::Base
  belongs_to :startStop, :class_name => 'Stop', :foreign_key => 'startStop_id'
  belongs_to :endStop, :class_name => 'Stop', :foreign_key => 'endStop_id'

  def friendly_name
    "#{startStop.city_with_place} - #{endStop.city_with_place} - #{price}PLN"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards, :through => :reward_statuses
  has_many :reservations
  has_many :secretary_hourses
  has_many :driver_rides

  validates_presence_of :firstName, :lastName

  def friendly_name
    "#{firstName} #{lastName}"
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :rides
  has_many :refuelings

  validates_presence_of :brand, :model

  def friendly_name
    "#{id}: #{brand} - #{model}"
  end
end

app/models/week_day.rb
class WeekDay < ActiveRecord::Base
  has_and_belongs_to_many :rides
  has_and_belongs_to_many :secretary_hours

  def friendly_name
    case id
      when 1
        "Pn"
      when 2
        "Wt"
      when 3
        "Śr"
      when 4
        "Cz"
      when 5
        "Pt"
      when 6
        "Sb"
      when 7
        "Nd"
      else
        puts "You gave me #{id} -- I have no idea what to do with that."
    end
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_check_owner, only: [:index, :new, :create, :edit, :update, :destroy]

  def new
    @reward = Reward.new
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      if params[:reward][:avatar].blank?
        redirect_to @reward
      else
        render action: :crop
      end
    else
      flash[:alert] = "Wystąpiły błędy"
      render 'new'
    end
  end


  def update
    @reward = Reward.find(params[:id])

    if @reward.update(reward_params)
      if params[:reward][:avatar].blank?
        redirect_to @reward
      else
        render action: :crop
      end
    else
      flash[:alert] = "Wystąpiły błędy"
      render 'edit'
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    redirect_to rewards_path
  end

  def show
    @reward = Reward.find(params[:id])
  end

  def index
    @rewards = Reward.all
  end

  def crop
    debugger
  end

  private

  def reward_params
    params.require(:reward).permit(:title, :description, :price, :avatar, :crop_x, :crop_y, :crop_w, :crop_h)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/refuelings_helper.rb
module RefuelingsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def link_to_function(name, *args, &block)
    html_options = args.extract_options!.symbolize_keys

    function = block_given? ? update_page(&block) : args[0] || ''
    onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'

    content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end

end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/rewards/_form.html.erb
<%= form_for @reward, :html => { :multipart => true, class: 'form-signin'  } do |f| %>

  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2>
        Wystąpiły następujące błędy
      </h2>
      <ul>
        <% @reward.errors.full_messages.each do |msg| %>
          <li>Pole <%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :title %><br>
  <%= f.text_field :title, autofocus: true , class: "form-control", required: true %>

  <%= f.label :description %><br>
  <%= f.text_area :description, class: "form-control", required: true %>

  <%= f.label :price %><br>
  <%= f.text_field :price, type: "number", class: "form-control", required: true %>

  <%= f.label :avatar  %><br>
  <%= f.file_field :avatar , accept: "image/*", class: "form-control", required: true %>

  <p>
  <table>
    <tr>
      <td><%= f.submit 'Zapisz', class: 'btn btn-primary'%></td>
      <td style="padding-left:5px;"><%= link_to 'Powrót', rewards_path, class: 'btn btn-default' %></td>
    </tr>
  </table>
  </p>
<% end %>

app/views/rewards/crop.html.erb
<% content_for (:head) do %>
  <%= stylesheet_link_tag "jquery.Jcrop" %>
  <%= javascript_include_tag "jquery.Jcrop.min" %>
  <script type="text/javascript">
    function update_crop(coords) {
      var ratio = <%= @reward.avatar_geometry(:original).width %> / <%= @reward.avatar_geometry(:large).width %>;
      $('#crop_x').val(Math.floor(coords.x * ratio));
      $('#crop_y').val(Math.floor(coords.y * ratio));
      $('#crop_w').val(Math.floor(coords.w * ratio));
      $('#crop_h').val(Math.floor(coords.h * ratio));
    }
    $(function() {
      $('#cropbox').Jcrop({
        onChange: update_crop,
        onSelect: update_crop,
        setSelect: [0, 0, 500, 500],
        aspectRatio: 1.25
      });
    });
  </script>
<% end %>

<%= image_tag @reward.avatar.url(:large), :id => "cropbox" %>

<%= form_for @reward, :html => { :multipart => true } do |form| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= form.hidden_field attribute, :id => attribute %>
  <% end %>
  <%= form.submit 'Przytnij', class: 'btn btn-primary' %>
<% end %>

app/views/rewards/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6 col-md-offset-3">
    <h1 class="text-center login-title">Edytuj nagrodę</h1>
    <hr>
    <div class="account-wall">
      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/rewards/index.html.erb
<hr style="margin:40px 0;">

<h1 style="float:left;">Nagrody</h1>
<%= link_to 'Dodaj nową', new_reward_path, class: 'btn btn-primary', style: 'float:right; margin-top:25px;' %>

<hr style="clear:both;"/>

<table class="table table-striped table-hover">
  <tr>
    <th>Tytuł</th>
    <th>Opis</th>
    <th>Cena</th>
    <th style="width:5%;"></th>
    <th style="width:5%;"></th>
  </tr>
  <% @rewards.order(:id).each do |reward| %>
    <tr>
      <td class="clickable-row" data-href='<%= reward_path(reward) %>'><%= reward.title %></td>
      <td class="clickable-row" data-href='<%= reward_path(reward) %>'><%= reward.description %></td>
      <td class="clickable-row" data-href='<%= reward_path(reward) %>'><%= reward.price %> pkt.</td>
      <td><%= link_to 'Edycja', edit_reward_path(reward), class: 'btn btn-default btn-sm' %></td>
      <td><%= link_to 'Usuń', reward_path(reward), method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć nagrodę?'}, class: 'btn btn-primary btn-sm' %></td>
    </tr>
  <% end %>
</table>

app/views/rewards/new.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6 col-md-offset-3">
    <h1 class="text-center login-title">Dodaj nagrodę</h1>
    <hr>
    <div class="account-wall">
      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/rewards/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= @reward.try(:title) %></h1>

  </div>
</div>
<!-- /.row -->

<!-- Portfolio Item Row -->
<div class="row">

  <div class="col-md-6">
    <%= image_tag @reward.avatar.url(:large), class: 'img-responsive' %>
  </div>

  <div class="col-md-6">
    <h3>Opis nagrody</h3>
    <p><%= @reward.try(:description) %></p>
    <h3>Cena</h3>
    <h4><%= @reward.try(:price) %> PKT</h4>
    <h3>Działania</h3>

    <% if current_user.try(:owner?) %>

      <%= link_to 'Edycja', edit_reward_path(@reward), class: 'btn btn-primary btn-sm' %>
      <%= link_to 'Usuń', reward_path(@reward), method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć nagrodę?'}, class: 'btn btn-primary btn-sm' %>

    <% end %>

    <%= link_to 'Odbierz nagrodę', reward_statuses_path(:reward_status => { :reward_id => @reward.id, user_id: current_user.try(:id)}), :method => :post, class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Powrót', :back , class: 'btn btn-default btn-sm' %>
  </div>

</div>