config/routes.rb
Rails.application.routes.draw do
  resources :vehicles, :rides, :routes, :stops_prices, :stops, :rewards, :reservations, :driver_rides, :secretary_hours, :refuelings
  resources :reward_statuses, except: :new
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  root 'pages#index'
  get 'price_list' => 'pages#price_list'
  get 'before_new' => 'reservations#before_new'
  get 'rewards_list' => 'pages#rewards_list'
  post 'payment' => 'reservations#payment'
  post 'payment_process' => 'reservations#payment_process'

end

app/models/driver_ride.rb
class DriverRide < ActiveRecord::Base
  belongs_to :user
  belongs_to :ride
  has_many :reservations

  validates_presence_of :date, :ride_id
end

app/models/order_of_stop.rb
class OrderOfStop < ActiveRecord::Base
  belongs_to :stop
  belongs_to :route
end

app/models/refueling.rb
class Refueling < ActiveRecord::Base
  belongs_to :vehicle

  validates_presence_of :capacity, :price
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :driver_ride
  belongs_to :stops_price
  attr_accessor :ride

  def friendly_name
    "#{driver_ride.try(:ride).try(:route).try(:friendly_name)} <strong>#{date} #{driver_ride.try(:ride).startTime.strftime("%k:%M")}</strong>"
  end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :users, :through => :reward_statuses
  validates_presence_of :title,:description, :price

  has_attached_file :avatar, :styles => { :medium => "300x300>", :small => "100x100#", :large => "700x700>" },
                    :processors => [:cropper],
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :processing
  after_update :reprocess_avatar, :if => :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
  end

  private
  def reprocess_avatar
    return unless (cropping? && !processing)
    self.processing = true
    avatar.reprocess!
    self.processing = false
  end

end

app/models/reward_status.rb
class RewardStatus < ActiveRecord::Base
  belongs_to :reward
  belongs_to :user

  def status_name
    case status
      when 1
        "Oczekuje na rozpatrzenie"
      when 2
        "Oczekuje na wysyłkę"
      when 3
        "Wysłano"
      else
        "Błąd"
    end
  end
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  has_many :driver_rides
  belongs_to :vehicle
  belongs_to :route
  has_and_belongs_to_many :week_days

  def friendly_name
    days = ""
    week_days.each do |w|
      days += w.friendly_name + " "
    end
    "#{route.friendly_name} - #{startTime.strftime("%k:%M")} - #{end_time} - #{days}"
  end

  def end_time
    (startTime + route.order_of_stops.order(:order).last.time * 60).strftime("%k:%M")
  end

  def stop_time stop
    if time =  route.order_of_stops.order(:order).find(stop).time
      (startTime + time * 60).strftime("%k:%M")
    else
      (startTime).strftime("%k:%M")
    end
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :rides
  has_many :order_of_stops, :dependent => :destroy
  has_many :stops, :through => :order_of_stops

  accepts_nested_attributes_for :order_of_stops, :allow_destroy => true

  def friendly_name
    "#{id}: #{order_of_stops.order(:order).first.try(:stop).try(:city_with_place)} -> #{order_of_stops.order(:order).last.try(:stop).try(:city_with_place)}"
  end
end

app/models/secretary_hours.rb
class SecretaryHours < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :week_days
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  has_many :routes, :through => :order_of_stops
  has_many :stops_prices_start, :class_name => 'StopsPrice', :foreign_key => 'startStop_id'
  has_many :stops_prices_end, :class_name => 'StopsPrice', :foreign_key => 'endStop_id'

  validates_presence_of :city, :place

  def city_with_place
    "#{city} - #{place}"
  end
end

app/models/stops_price.rb
class StopsPrice < ActiveRecord::Base
  belongs_to :startStop, :class_name => 'Stop', :foreign_key => 'startStop_id'
  belongs_to :endStop, :class_name => 'Stop', :foreign_key => 'endStop_id'

  def friendly_name
    "#{startStop.city_with_place} - #{endStop.city_with_place} - #{price}PLN"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards, :through => :reward_statuses
  has_many :reservations
  has_many :secretary_hourses
  has_many :driver_rides

  validates_presence_of :firstName, :lastName

  def friendly_name
    "#{firstName} #{lastName}"
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :rides
  has_many :refuelings

  validates_presence_of :brand, :model

  def friendly_name
    "#{id}: #{brand} - #{model}"
  end
end

app/models/week_day.rb
class WeekDay < ActiveRecord::Base
  has_and_belongs_to_many :rides
  has_and_belongs_to_many :secretary_hours

  def friendly_name
    case id
      when 1
        "Pn"
      when 2
        "Wt"
      when 3
        "Śr"
      when 4
        "Cz"
      when 5
        "Pt"
      when 6
        "Sb"
      when 7
        "Nd"
      else
        puts "You gave me #{id} -- I have no idea what to do with that."
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def link_to_function(name, *args, &block)
    html_options = args.extract_options!.symbolize_keys

    function = block_given? ? update_page(&block) : args[0] || ''
    onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'

    content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end

end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <hr style="margin: 20px 0">
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Michal 2017</p>
      </div>
    </div>
  </div>
</footer>

<script>
  $('.carousel').carousel({
    interval: 5000 //changes the speed
  })
  // clickable table row
  jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
      window.document.location = $(this).data("href");
    });
  });
</script>

app/views/layouts/_header.html.erb
<head>
  <title>KK-Bus | Nowa jakość podróży</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= yield(:head) %>
</head>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top affix" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'KK-Bus', root_path, :class => 'navbar-brand' %> <!--image_tag("img/brand.png", :border=>0, :class => 'logo-top') -->
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Cennik', price_list_path %></li>
        <li><%= link_to 'Nagrody', rewards_list_path %></li>
        <% if user_signed_in? %><li><%= link_to 'Rezerwacja', reservations_path %></li><% end %>
        <% if current_user.try(:secretary?) or current_user.try(:driver?) or current_user.try(:owner?)%><li><%= link_to 'Przejazdy kierowców', driver_rides_path %></li><% end %>
        <% if current_user.try(:driver?) %><li><a href="<%= refuelings_path %>">Tankowania</a></li><% end %>
        <% if current_user.try(:owner?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Panel administratora<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="<%= rewards_path %>">Nagrody</a></li>
              <li><a href="<%= stops_path %>">Przystanki</a></li>
              <li><a href="<%= stops_prices_path %>">Ceny przejazdów</a></li>
              <li><a href="<%= refuelings_path %>">Tankowania</a></li>
              <li><a href="<%= routes_path %>">Trasy</a></li>
              <li><a href="<%= vehicles_path %>">Pojazdy</a></li>
              <li><a href="<%= rides_path %>">Przejazdy</a></li>
              <li><a href="<%= reward_statuses_path %>">Statusy nagród</a></li>
              <li><a href="<%= secretary_hours_path %>">Godziny pracy sekretarek</a></li>
              <li><a href="<%= new_user_registration_path %>">Dodawanie użytkownika</a></li>
            </ul>
          </li>
        <% end %>

      </ul>

      <div class="navbar-text navbar-nav navbar-right">
        <% if user_signed_in? %>
          <strong><%= link_to current_user.firstName + " " + current_user.lastName, edit_user_registration_path, :class => 'navbar-link' %></strong>
          <%= link_to "Pkt: #{current_user.points}", rewards_list_path, :class => 'navbar-link' %> |
          <%= link_to "Wyloguj", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Rejestracja", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Logowanie", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div>

  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_notifications.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible alert-custom" role="alert">
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible alert-custom" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_slider.html.erb
<!-- Half Page Image Background Carousel Header -->
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url(<%= image_path("slide02.jpg") %>);"></div>
      <div class="carousel-caption">
        <h2>Zaufało nam już ponad milion klientów</h2>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url(<%= image_path("slide03.jpg") %>);"></div>
      <div class="carousel-caption">
        <h2>Z nami zawsze dotrzesz do celu</h2>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url(<%= image_path("slide04.jpg") %>);"></div>
      <div class="carousel-caption">
        <h2>I nigdy się nie zgubisz</h2>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<%=render 'layouts/header' %>
<body>
<%=render 'layouts/navbar' %>
<%=render 'layouts/notifications' %>

<%=render 'layouts/slider' %>

<div class="container">
<%= yield %>
</div>

<%=render 'layouts/footer' %>

</body>
</html>